language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L http://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "sunjido" -p "211140san"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/lab10-backend.jar -t sunjido/se234-lab10-backend  .
- docker push sunjido/se234-lab10-backend
- docker pull sunjido/se234-lab10-client
script:
- docker-compose -H "tcp://52.14.107.181:2000" up -d
cache:
  directories:
  - "$HOME/.m2"
